In [1]:
import numpy as np

In [6]:
W = np.matrix([[3,4],[5,6],[7,8],[9,10]])
W0 = np.matrix([1,2,3,5]).reshape((4,1))

In [3]:
W.shape

(4, 2)

In [7]:
W0.shape

(4, 1)

In [8]:
W0

matrix([[1],
        [2],
        [3],
        [5]])

In [9]:
W

matrix([[ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [12]:
X = np.matrix([50,60]).reshape((2,1))

In [13]:
X.shape

(2, 1)

In [14]:
X

matrix([[50],
        [60]])

In [17]:
Z=W@X+W0

In [18]:
Z

matrix([[ 391],
        [ 612],
        [ 833],
        [1055]])

In [19]:
np.matmul(W,X)+W0

matrix([[ 391],
        [ 612],
        [ 833],
        [1055]])

In [20]:
np.dot(W,X)+W0

matrix([[ 391],
        [ 612],
        [ 833],
        [1055]])

In [21]:
### relu
def relu(x):
    x[x<0]=0
    return x

In [22]:
relu(Z)

matrix([[ 391],
        [ 612],
        [ 833],
        [1055]])

In [24]:
relu(np.matrix([[  2],
        [ 13],
        [ -4],
        [-15]]))

matrix([[ 2],
        [13],
        [ 0],
        [ 0]])

In [25]:
def relu_scalar(x):
    if x<0:
        return 0
    else:
        return x

In [27]:
relu_scalar(3)

3

In [28]:
Z.shape

(4, 1)

In [29]:
V = np.matrix([[1,1,1,1],[1,1,1,1]])
V.shape

(2, 4)

In [33]:
V0=np.matrix([2,2]).reshape((2,1))

In [34]:
V0.shape

(2, 1)

In [37]:
V@relu(Z)+V0

matrix([[2893],
        [2893]])

In [44]:
### Organize your code
## max value in a one dimensional array
## def min_one_dim():
    ## return
## max value of a 3 dimensional array:
## def max_3d():
    ## return
## max value of a 4 d array:
## def max_4d():
    ## return 
## if 1d array, max(), then finds max for 1 array
## if its 2d array, max(), then finds max for 2d array

class MLSessions():
    ## constructor
    def __init__(self,session_name,duration):
        self.session_name = session_name
        self.duration = duration
    def display(self):
        return {'session_name':self.session_name,'duration':self.duration}
        

In [45]:
cls = MLSessions(session_name=['afkanf','ajkskld'],duration=[80,90])

In [40]:
print(dir(cls))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'display', 'duration', 'session_name']


In [41]:
cls.session_name

['afkanf', 'ajkskld']

In [42]:
cls.duration

[80, 90]

In [46]:
cls.display()

{'session_name': ['afkanf', 'ajkskld'], 'duration': [80, 90]}

In [47]:
## Add method to this class which gives the sum of all durations
class MLSessions():
    ## constructor
    def __init__(self,session_name,duration):
        self.session_name = session_name
        self.duration = duration
    def display(self):
        return {'session_name':self.session_name,'duration':self.duration}
    def total_dur(self):
        return sum(self.duration)

In [48]:
cls = MLSessions(session_name=['afkanf','ajkskld'],duration=[80,90])

In [49]:
cls.total_dur()

170

In [50]:
### Define a class that can take a 2 by 1 matrix (X) and do a forward pass on it
W = np.matrix([[3,4],[5,6],[7,8],[9,10]])
W0 = np.matrix([1,2,3,5]).reshape((4,1))
V = np.matrix([[1,1,1,1],[1,1,1,1]])
V0=np.matrix([2,2]).reshape((2,1))

In [ ]:
class NN():
    
    def __init__(self):
        self.W = np.matrix([[2,4],[5,6],[7,8],[9,10]])
        self.W0 = np.matrix([1,2,3,5]).reshape((4,1))
        self.V = np.matrix([[2,2,1,1],[1,1,1,1]])
        self.V0 = np.matrix([2,2]).reshape((2,1))
    
    def relu(self,Z):
        Z[Z<0] = 0
        return Z
    
    def forward(self,X):
        Z = self.W@X+self.W0
        activation = self.relu(Z)
        Z = self.V@activation + self.V0
        return self.relu(Z)
        

In [62]:
X

matrix([[50],
        [60]])

In [63]:
n=NN()

In [65]:
print(dir(n))

['V', 'V0', 'W', 'W0', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'forward', 'relu']


In [66]:
n.forward(X)

matrix([[2893],
        [2893]])